#!/bin/sh

echo 'Changing to /tmp'
cd /tmp
rm -rf klotski

echo 'Checkouting klotski from cvs'
cvs -d :ext:philippe@cvs.freehackers.org:/usr/olocal/cvsroot export -r HEAD -d klotski phil/devel/klotski
cd klotski

echo 'Generating pixmaps'
export LD_LIBRARY_PATH=/usr/local/lib:/opt/be/qt-copy/lib
cd pixmaps
python generate_pix.py
cd ..
rm -f makerelease


echo 'Making unix release'
cd ..
tar jcvf ~/klotski-1-2.tar.bz2 klotski/*
echo done.

cd klotski
echo 'Making Windows release'

echo 'Converting files'

cd ..
zip -r ~/klotski-1-2.zip klotski
echo done.



